---
# Copyright 2022 Sam Darwin
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: build_docs

on:
  pull_request:
    paths:
      - 'build_docs/**'
  push:
    paths:
      - 'build_docs/**'
    branches:
      - master
      - develop
      - feature/**

jobs:
  linux:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: ubuntu:22.04
            packages: python2
            skiplist: auto_index
          # - os: ubuntu-latest
          #   container: ubuntu:20.04
          #   packages: python
          #   skiplist: auto_index
          - os: ubuntu-latest
            container: ubuntu:22.04
            packages: python2
            # skiplist:
            flags: "--boostrelease"
          # - os: ubuntu-latest
          #   container: ubuntu:20.04
          #   packages: python
          #   # skiplist:
          #   flags: "--boostrelease"
          #   # Jinja 3.1.0 and later have dropped support for Python 3.6 and therefore won't run on Ubuntu 18.04. Removing tests for Ubuntu 18.

    timeout-minutes: 720
    runs-on: ${{matrix.os}}
    container: ${{matrix.container}}

    steps:

      - uses: actions/checkout@v2

      - name: docs
        run: |
            set -x
            set -e
            apt-get update
            DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata
            apt-get install -y git sudo
            apt-get install -y ${{ matrix.packages }}
            if [ ! -f /usr/bin/python ]; then
                ln -s /usr/bin/python2 /usr/bin/python
            fi

            cp build_docs/linuxdocs.sh /usr/local/bin/

            # mkdir -p /opt/github/boostorg
            # cd /opt/github/boostorg
            # git clone -b "develop" --depth 1 "https://github.com/boostorg/boost.git"
            # cd boost
            # git submodule update --init

            # # Run at least one full build that installs everything
            # cd libs/accumulators
            # # linuxdocs.sh ${{ matrix.flags }}
            # linuxdocs.sh --boostrootsubdir ${{ matrix.flags }}
            # cd ../..

            textpart1='#!/bin/bash
            reponame=$1
            echo "reponame is $reponame"
            skiplist="'

            textpart2="${{ matrix.skiplist }}"

            textpart3='"
            # jump ahead to continue testing

            if [[ "$reponame" =~ ^[a-r] ]]; then
            # if [[ "$reponame" =~ ^[9] ]]; then
               echo "skipping ahead X letters"
            elif [[ "$skiplist" =~ $reponame ]]; then
                echo "repo in skiplist"
            else
                # linuxdocs.sh --quick
                linuxdocs.sh --boostrootsubdir --skip-packages '

            textpart4=${{ matrix.flags }}
            textpart5='
                if [[ $? != 0 ]]; then
                    echo "..failed. DOCS BUILD FAILED. LIBRARY $reponame"
                else
                    echo "LIBRARY $reponame SUCCEEDED."
                fi
            fi
            '

            textsource="${textpart1}${textpart2}${textpart3}${textpart4}${textpart5}"
            echo "$textsource" > /usr/local/bin/runlinuxdocsquick
            chmod 755 /usr/local/bin/runlinuxdocsquick
            echo "checking runlinuxdocsquick"
            cat /usr/local/bin/runlinuxdocsquick
            #             allrepos="
            # https://github.com/boostorg/accumulators.git
            # https://github.com/boostorg/algorithm.git
            # https://github.com/boostorg/align.git
            # https://github.com/boostorg/any.git
            # https://github.com/boostorg/array.git
            # https://github.com/boostorg/asio.git
            # https://github.com/boostorg/assert.git
            # https://github.com/boostorg/assign.git
            # https://github.com/boostorg/atomic.git
            # https://github.com/boostorg/auto_index.git
            # https://github.com/boostorg/bcp.git
            # https://github.com/boostorg/beast.git
            # https://github.com/boostorg/bimap.git
            # https://github.com/boostorg/bind.git
            # https://github.com/boostorg/boostbook.git
            # https://github.com/boostorg/boostdep.git
            # https://github.com/boostorg/boost_install.git
            # https://github.com/boostorg/build.git
            # https://github.com/boostorg/callable_traits.git
            # https://github.com/boostorg/check_build.git
            # https://github.com/boostorg/chrono.git
            # https://github.com/boostorg/circular_buffer.git
            # https://github.com/boostorg/cmake.git
            # https://github.com/boostorg/compatibility.git
            # https://github.com/boostorg/compute.git
            # https://github.com/boostorg/concept_check.git
            # https://github.com/boostorg/config.git
            # https://github.com/boostorg/container.git
            # https://github.com/boostorg/container_hash.git
            # https://github.com/boostorg/context.git
            # https://github.com/boostorg/contract.git
            # https://github.com/boostorg/conversion.git
            # https://github.com/boostorg/convert.git
            # https://github.com/boostorg/core.git
            # https://github.com/boostorg/coroutine2.git
            # https://github.com/boostorg/coroutine.git
            # https://github.com/boostorg/crc.git
            # https://github.com/boostorg/date_time.git
            # https://github.com/boostorg/describe.git
            # https://github.com/boostorg/detail.git
            # https://github.com/boostorg/dll.git
            # https://github.com/boostorg/docca.git
            # https://github.com/boostorg/dynamic_bitset.git
            # https://github.com/boostorg/endian.git
            # https://github.com/boostorg/exception.git
            # https://github.com/boostorg/fiber.git
            # https://github.com/boostorg/filesystem.git
            # https://github.com/boostorg/flyweight.git
            # https://github.com/boostorg/foreach.git
            # https://github.com/boostorg/format.git
            # https://github.com/boostorg/functional.git
            # https://github.com/boostorg/function.git
            # https://github.com/boostorg/function_types.git
            # https://github.com/boostorg/fusion.git
            # https://github.com/boostorg/geometry.git
            # https://github.com/boostorg/gil.git
            # https://github.com/boostorg/graph.git
            # https://github.com/boostorg/graph_parallel.git
            # https://github.com/boostorg/hana.git
            # https://github.com/boostorg/headers.git
            # https://github.com/boostorg/heap.git
            # https://github.com/boostorg/histogram.git
            # https://github.com/boostorg/hof.git
            # https://github.com/boostorg/icl.git
            # https://github.com/boostorg/inspect.git
            # https://github.com/boostorg/integer.git
            # https://github.com/boostorg/interprocess.git
            # https://github.com/boostorg/interval.git
            # https://github.com/boostorg/intrusive.git
            # https://github.com/boostorg/io.git
            # https://github.com/boostorg/iostreams.git
            # https://github.com/boostorg/iterator.git
            # https://github.com/boostorg/json.git
            # https://github.com/boostorg/lambda2.git
            # https://github.com/boostorg/lambda.git
            # https://github.com/boostorg/leaf.git
            # https://github.com/boostorg/lexical_cast.git
            # https://github.com/boostorg/litre.git
            # https://github.com/boostorg/locale.git
            # https://github.com/boostorg/local_function.git
            # https://github.com/boostorg/lockfree.git
            # https://github.com/boostorg/log.git
            # https://github.com/boostorg/logic.git
            # https://github.com/boostorg/math.git
            # https://github.com/boostorg/metaparse.git
            # https://github.com/boostorg/more.git
            # https://github.com/boostorg/move.git
            # https://github.com/boostorg/mp11.git
            # https://github.com/boostorg/mpi.git
            # https://github.com/boostorg/mpl.git
            # https://github.com/boostorg/msm.git
            # https://github.com/boostorg/multi_array.git
            # https://github.com/boostorg/multi_index.git
            # https://github.com/boostorg/multiprecision.git
            # https://github.com/boostorg/nowide.git
            # https://github.com/boostorg/numeric_conversion.git
            # https://github.com/boostorg/odeint.git
            # https://github.com/boostorg/optional.git
            # https://github.com/boostorg/outcome.git
            # https://github.com/boostorg/parameter.git
            # https://github.com/boostorg/parameter_python.git
            # https://github.com/boostorg/pfr.git
            # https://github.com/boostorg/phoenix.git
            # https://github.com/boostorg/poly_collection.git
            # https://github.com/boostorg/polygon.git
            # https://github.com/boostorg/pool.git
            # https://github.com/boostorg/predef.git
            # https://github.com/boostorg/preprocessor.git
            # https://github.com/boostorg/process.git
            # https://github.com/boostorg/program_options.git
            # https://github.com/boostorg/property_map.git
            # https://github.com/boostorg/property_map_parallel.git
            # https://github.com/boostorg/property_tree.git
            # https://github.com/boostorg/proto.git
            # https://github.com/boostorg/ptr_container.git
            # https://github.com/boostorg/python.git
            # https://github.com/boostorg/quickbook.git
            # https://github.com/boostorg/qvm.git
            # https://github.com/boostorg/random.git
            # https://github.com/boostorg/range.git
            # https://github.com/boostorg/ratio.git
            # https://github.com/boostorg/rational.git
            # https://github.com/boostorg/regex.git
            # https://github.com/boostorg/safe_numerics.git
            # https://github.com/boostorg/scope_exit.git
            # https://github.com/boostorg/serialization.git
            # https://github.com/boostorg/signals2.git
            # https://github.com/boostorg/smart_ptr.git
            # https://github.com/boostorg/sort.git
            # https://github.com/boostorg/spirit.git
            # https://github.com/boostorg/stacktrace.git
            # https://github.com/boostorg/statechart.git
            # https://github.com/boostorg/static_assert.git
            # https://github.com/boostorg/static_string.git
            # https://github.com/boostorg/stl_interfaces.git
            # https://github.com/boostorg/system.git
            # https://github.com/boostorg/test.git
            allrepos="
            https://github.com/boostorg/thread.git
            https://github.com/boostorg/throw_exception.git
            https://github.com/boostorg/timer.git
            https://github.com/boostorg/tokenizer.git
            https://github.com/boostorg/tti.git
            https://github.com/boostorg/tuple.git
            https://github.com/boostorg/type_erasure.git
            https://github.com/boostorg/type_index.git
            https://github.com/boostorg/typeof.git
            https://github.com/boostorg/type_traits.git
            https://github.com/boostorg/ublas.git
            https://github.com/boostorg/units.git
            https://github.com/boostorg/unordered.git
            https://github.com/boostorg/url.git
            https://github.com/boostorg/utility.git
            https://github.com/boostorg/uuid.git
            https://github.com/boostorg/variant2.git
            https://github.com/boostorg/variant.git
            https://github.com/boostorg/vmd.git
            https://github.com/boostorg/wave.git
            https://github.com/boostorg/winapi.git
            https://github.com/boostorg/xpressive.git
            https://github.com/boostorg/yap.git
            "
            # "full" install at least with packages
            firstrepo="https://github.com/boostorg/accumulators.git"
            git clone $firstrepo
            reposhortname=$(basename -s .git $firstrepo)
            cd ${reposhortname}
            linuxdocs.sh --boostrootsubdir
            pwd
            cd ..
            pwd

            # git submodule foreach 'runlinuxdocsquick $name'
            for repo in $allrepos; do
                git clone $repo
                reposhortname=$(basename -s .git $repo)
                cd ${reposhortname}
                runlinuxdocsquick
                pwd
                cd ..
                pwd
            done
